src/reyna/deluna/Ex2.java
Signed-off-by: Reyna Pauline de Luna <reynapauline@gmail.com>
=> Exercise 2

src/instructor/templates/Ex2.java
=> Exercise 2 - Lim Keith

src/bato/Ex2.java
Signed-off-by: Ryna Bato <rynabato@gmail.com>
=> Exercise 2 Bato, Ryna

src/joshua/juanson/Ex2.java
Signed-off-by: Joshua Juanson <joshua_juanson@dlsu.edu.ph>
=> Exercise 2 - Juanson

src/instructor/Matthew/Reyes/Ex2.java
Signed-off-by: Matthew Reyes <reyesmatthew@gmail.com>
=> Exercise 2 Reyes

src/instructor/templates/Ex1.java
=> Ex2-martinez

src/aranguren/bernadette/Ex2.java, src/instructor/templates/Ex2.java
=> Ex2-Aranguren

src/aranguren/bernadette/Ex2.java, src/aranguren/bernadette/Item.java, src/aranguren/bernadette/PurchaseOrder.java
=> Ex2.2-Aranguren

src/angelica/olan/PurchaseOrder.java
Signed-off-by: angelicaolan <olan.angelica@gmail.com>
=> Sumbission

src/martina/martinez/Ex3.java, src/martina/martinez/Ex3/Item.java, src/martina/martinez/Ex3/PurchaseOrder.java, src/martina/martinez/Ex3/TotalPrice.java, src/martina/martinez/Ex4/Item.java, src/martina/martinez/Ex4/PurchaseOrder.java, src/martina/martinez/Ex4/TotalPrice.java
=> Ex4 commit

src/matthew/reyes/Item.java, src/matthew/reyes/getTotalPOAmount.java, src/matthew/reyes/purchaseorder.java
Signed-off-by: Matthew Reyes <reyesmatthew@gmail.com>
=> submission

src/martina/martinez/Ex1.java
=> Ex1 commit

src/arvin/ymson/Exercise1_1.java, src/arvin/ymson/Exercise1_2.java, src/arvin/ymson/Exercise2_1.java, src/arvin/ymson/Exercise2_2.java, src/arvin/ymson/Exercise3.java, src/arvin/ymson/Exercise4.java, src/arvin/ymson/PurchaseOrder.java
Signed-off-by: Arvin Ymson <Arvin Ymson>
=> Submissions

src/ryna/bato/Item2.java, src/ryna/bato/PurchaseOrder2.java, src/totalpurchase.java
Signed-off-by: Ryna Bato <rynabato@gmail.com>
=> Exercise 3-bato

src/tommy/lim/Item.java, src/tommy/lim/PO.java, src/tommy/lim/getTotalPOAmount.java
Signed-off-by: vielkers <vielka_carvajal@dlsu.edu.ph>
=> Submission for Ex3

src/martina/martinez/Ex1.java
=> Ex1 resubmit

src/anton/santos/PurchaseOrder/PurchaseOrder.java, src/anton/santos/PurchaseOrder/TotalPurchase.java
Signed-off-by: Anton Santos <aysantos.12@gmail.com>
=> Ex 5 Static Counter

src/tommy/lim/Ex4/Item.java, src/tommy/lim/Ex4/PO.java, src/tommy/lim/Ex4/getTotalPOAmount.java
Signed-off-by: Tommy Lim <tommy_lim@dlsu.edu.ph>
=> Submission Exercise 4

src/anton/santos/PurchaseOrder/ItemsPrice.java, src/anton/santos/PurchaseOrder/TotalPurchase.java
Signed-off-by: splongklong <anton_santos@dlsu.edu.ph>
=> Ex 6 New Class ToString

src/matthew/reyes/Item.java, src/matthew/reyes/getTotalPOAmount.java
Signed-off-by: Matthew Reyes <reyesmatthew@gmail.com>
=> added item for ex3

src/aranguren/bernadette/Company.java, src/aranguren/bernadette/Item.java, src/aranguren/bernadette/PurchaseOrder.java
=> Ex5-Aranguren

src/martina/martinez/Ex6/Company.java, src/martina/martinez/Ex6/Item.java, src/martina/martinez/Ex6/PurchaseOrder.java, src/martina/martinez/Ex6/TotalPrice.java, src/martina/martinez/Ex6/abc.java
=> commit ex6

src/aranguren/bernadette/GUI.form, src/aranguren/bernadette/GUI.java
=> GUI Exercise - Aranguren

src/tommy/lim/UI/Exercise.form, src/tommy/lim/UI/Exercise.java, src/tommy/lim/UI/Utility.java
Signed-off-by: Tommy Lim <tommy_lim@dlsu.edu.ph>
=> GUI form exercise

src/jason/lau/Ex7/Ex7.form, src/jason/lau/Ex7/Ex7.java, src/jason/lau/Ex7/Source.java
Signed-off-by: Jason Lau <jason_lau@dlsu.edu.ph>
=> Lau.Exercise 7

src/aranguren/bernadette/Ex5/Company.java, src/aranguren/bernadette/Ex5/Item.java, src/aranguren/bernadette/Ex5/PurchaseOrder.java
=> Ex5 - Aranguren (resubmit - package)

src/aranguren/bernadette/Ex6/Company.java, src/aranguren/bernadette/Ex6/Item.java, src/aranguren/bernadette/Ex6/PurchaseOrder.java
=> Ex6 - Aranguren

src/keith/lim/TermProject/Finances.java, src/keith/lim/TermProject/Items.java, src/keith/lim/TermProject/PO.java, src/keith/lim/TermProject/PR.java, src/keith/lim/TermProject/Supplier.java, src/keith/lim/TermProject/Utilities.java, src/keith/lim/UI/Numbers.form, src/keith/lim/UI/Numbers.java, src/keith/lim/UI/Utilities.java, src/keith/lim/ex7/Company.java, src/keith/lim/ex7/Item.java, src/keith/lim/ex7/ItemsPrice.java, src/keith/lim/ex7/PO.java, src/keith/lim/ex7/PurchaseOrder.java
=> UI Exercise. Previously in wrong location.

src/keith/lim/ex6/Company.java, src/keith/lim/ex6/Item.java, src/keith/lim/ex6/PurchaseOrder.java
=> Exercise 6. Previously in wrong location.

src/keith/lim/ex5/Company.java, src/keith/lim/ex5/Item.java, src/keith/lim/ex5/PurchaseOrder.java
=> Exercise 5. Previously in wrong location.

src/keith/lim/ex3/Item.java, src/keith/lim/ex3/PO.java
=> Exercise 3. Previously placed in wrong folder.

src/keith/lim/Ex1.java
=> Exercise 1. Pushed wrong file last time.

src/aranguren/bernadette/Ex1.java
=> Ex1-Aranguren (resubmit)

src/anton/santos/Ex1.java, src/anton/santos/Ex34567/Item.java, src/anton/santos/Ex34567/ItemsPrice.java, src/anton/santos/Ex34567/PurchaseOrder.java, src/anton/santos/Ex34567/TotalPurchase.java, src/anton/santos/TermProj/Company.java, src/anton/santos/TermProj/PurchaseReceipt.java, src/anton/santos/TermProj/SunItems.java, src/anton/santos/TermProj/TDataBase.form, src/anton/santos/TermProj/TDataBase.java
Signed-off-by: Anton Santos <aysantos.12@gmail.com>
=> Anton Santos Exercises Submission

src/ysai/bravo/Ex3/ITEM.java, src/ysai/bravo/Ex3/PO.java, src/ysai/bravo/Ex3/PRICE.java
Signed-off-by: ysaibravo <ysaibravo@gmail.com>
=> Exercise 3

src/tommy/lim/Ex1.java
Signed-off-by: Tommy Lim <tommy_lim@dlsu.edu.ph>
=> Exercise 1

src/aranguren/bernadette/Ex8/Circle.java, src/aranguren/bernadette/Ex8/Perimeter.java, src/aranguren/bernadette/Ex8/Shape.java, src/aranguren/bernadette/Ex8/Test.java, src/aranguren/bernadette/Ex8/Triangle.java
=> Ex8-Aranguren

src/keith/lim/Project/Finances.java, src/keith/lim/Project/Items.java, src/keith/lim/Project/PO.java, src/keith/lim/Project/PR.java, src/keith/lim/Project/Supplier.java, src/keith/lim/Project/Testing.java, src/keith/lim/Project/Utilities.java, src/keith/lim/ex4/Item.java, src/keith/lim/ex4/PO.java, src/keith/lim/ex4/PurchaseOrder.java
pls ignore projects folder; that's for term project
=> Ex4 keith lim

src/keith/lim/ex7/Company.java, src/keith/lim/ex7/Item.java, src/keith/lim/ex7/PurchaseOrder.java
=> Exercise 7 - Final

src/ryna/bato/Ex8/Circle.java, src/ryna/bato/Ex8/Main.java, src/ryna/bato/Ex8/Perimeter.java, src/ryna/bato/Ex8/Shape.java, src/ryna/bato/Ex8/Triangle.java
Signed-off-by: Ryna Bato <rynabato@gmail.com>
=> exercise 8 bato

src/joshua/juanson/FinalVersionsExercises/Exercise1.java, src/joshua/juanson/FinalVersionsExercises/Exercise2.java, src/joshua/juanson/FinalVersionsExercises/Exercise3/Exercise3Item.java, src/joshua/juanson/FinalVersionsExercises/Exercise3/Exercise3PurchaseOrder.java, src/joshua/juanson/FinalVersionsExercises/Exercise3/Exercise3TotalAmount.java
Signed-off-by: Joshua Juanson <joshua_juanson@dlsu.edu.ph>
=> FinalExercise123

src/jason/lau/Counter/Counter.java, src/jason/lau/Counter/PurchaseOrder3.java, src/jason/lau/Ex5/Company.java, src/jason/lau/Ex5/CompanyPO.java, src/jason/lau/Ex5/PurchaseOrder4.java, src/jason/lau/Ex6/CompanyPO.java, src/jason/lau/Ex6/PurchaseOrder5.java, src/jason/lau/Ex7/Company.java, src/jason/lau/Ex7/CompanyPO.java, src/jason/lau/Ex7/PurchaseOrder6.java, src/jason/lau/Ex8/Circle.java, src/jason/lau/Ex8/Perimeter.java, src/jason/lau/Ex8/Shape.java, src/jason/lau/Ex8/Triangle.java, src/jason/lau/Ex9/Ex9.form, src/jason/lau/Ex9/Ex9.java, src/jason/lau/Ex9/Source.java
Signed-off-by: Jason Lau <jason_lau@dlsu.edu.ph>
=> COMPLETE SUBMISSION

src/macavinta/gianninah/ex7/company.java, src/macavinta/gianninah/ex7/item.java, src/macavinta/gianninah/ex9/form.form, src/macavinta/gianninah/ex9/form.java
Signed-off-by: giannninahmm <gianninah.macavinta@yahoo.com>
=> ex9 and ex7

src/joshua/juanson/TermProject/Eval.form, src/joshua/juanson/TermProject/Eval.java, src/joshua/juanson/TermProject/Login.form, src/joshua/juanson/TermProject/Login.java, src/joshua/juanson/TermProject/MainMenu.form, src/joshua/juanson/TermProject/MainMenu.java, src/joshua/juanson/TermProject/Quotation.form, src/joshua/juanson/TermProject/Quotation.java, src/joshua/juanson/TermProject/Raw.form, src/joshua/juanson/TermProject/Raw.java
Signed-off-by: Joshua Juanson <joshua_juanson@dlsu.edu.ph>
=> TermProject

src/arvin/ymson/Complete/Circle.java, src/arvin/ymson/Complete/PerimeterInterface.java, src/arvin/ymson/Complete/Shape.java, src/arvin/ymson/Complete/Triangle.java, src/arvin/ymson/Exercise8/Circle.java, src/arvin/ymson/Exercise8/PerimeterInterface.java, src/arvin/ymson/Exercise8/Shape.java, src/arvin/ymson/Exercise8/Triangle.java
Sir, this is the revised version for exercise 8. Thank you very much!
=> Complete Exercises

src/tommy/lim/Item.java, src/tommy/lim/PO.java, src/tommy/lim/getTotalPOAmount.java
Signed-off-by: Tommy Lim <tommy_lim@dlsu.edu.ph>
=> Revise for Ex3
